//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace motadblock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("motadblock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///#motadblock - do not add anything until after #end of motadblock
        ///0.0.0.0 adback.pinion.gg
        ///0.0.0.0 ads.intergi.com
        ///0.0.0.0 bin.pinion.gg
        ///0.0.0.0 blog.pinion.gg
        ///0.0.0.0 cdn.pinion.gg
        ///0.0.0.0 cp.pinion.gg
        ///0.0.0.0 crm.pinion.gg
        ///0.0.0.0 delivery.pinion.gg
        ///0.0.0.0 docs.pinion.gg
        ///0.0.0.0 kermit.pinion.gg
        ///0.0.0.0 legacy.pinion.gg
        ///0.0.0.0 log.pinion.gg
        ///0.0.0.0 mail.pinion.gg
        ///0.0.0.0 motd.pinion.gg
        ///0.0.0.0 motdgd.com
        ///0.0.0.0 ns1.pinion.gg
        ///0.0.0.0 ns2.pinion.gg
        ///0.0.0.0 ns3.pinion.gg
        ///0.0.0.0 ns4.pi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hostslist {
            get {
                return ResourceManager.GetString("hostslist", resourceCulture);
            }
        }
    }
}
